/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [index]
      ,[SHIPPING_LOCATION]
      ,[DEPARTMENT]
      ,[CATEGORY]
      ,[SUBCATEGORY]
      ,[BREADCRUMBS]
      ,[SKU]
      ,[PRODUCT_URL]
      ,[PRODUCT NAME]
      ,[BRAND]
      ,[PRICE RETAIL]
      ,[PRICE CURRENT]
      ,[PRODUCT SIZE]
      ,[PROMOTION]
      ,[RunDate]
      ,[tid]
  FROM [Walmart].[dbo].['WalMart Sales Report$']